### ISSUE TITLE
add pandas dependency

### ISSUE THREAD

**Issue by raylu** [gnaneshwar441/Business_Duration#11]
the `setup.py` in `business_duration-0.66.tar.gz` on the [pypi package](https://pypi.org/project/business-duration) doesn't list any dependencies, so installing just `business-duration` doesn't work

```
$ pip install business-duration
Collecting business-duration
  Using cached business_duration-0.66.tar.gz (3.6 kB)
Building wheels for collected packages: business-duration
  Building wheel for business-duration (setup.py) ... done
  Created wheel for business-duration: filename=business_duration-0.66-py3-none-any.whl size=3531 sha256=84256d20a5d64a15c0f184f01a4d8bbe1ebb62ae49cc599e05c2dad434bd2411
  Stored in directory: /home/[...]/.cache/pip/wheels/d1/14/35/d72e0ecc27aab87a21828ea28db2a05d8c5933c0e4952aa81d
Successfully built business-duration
Installing collected packages: business-duration
Successfully installed business-duration-0.66

$ python3 -c 'import business_duration; business_duration.businessDuration(None, None)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[...]/lib/python3.8/site-packages/business_duration/__init__.py", line 2, in businessDuration
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by gnaneshwar441** [comment]
Noted. Dependency issue is resolved. Kindly install new version business-duration-0.67
